implement dashboard service
cloudforet-io/api pull request #14
Opened 2022-11-01 13:54 UTC by stat-kwon

### Category
- [x] New feature
- [ ] Bug fix
- [ ] Improvement
- [ ] Refactor
- [ ] etc

### Description
A new dashboard proto buffer was created according to the dashboard's api document. The dashboard service includes the following resources.
- DomainDashboard
- ProjectDashboard
- Widget

2022-11-02 01:31 UTC, whdalsrnt requested changes
You need to change the protobuf spec.

2022-11-02 01:50 UTC, whdalsrnt requested changes

2022-11-02 01:50 UTC, whdalsrnt commented on proto/spaceone/api/dashboard/v1/domain_dashboard.proto
> +  google.protobuf.ListValue labels = 5;
Remove the `labels` filter

2022-11-02 01:50 UTC, whdalsrnt commented on proto/spaceone/api/dashboard/v1/project_dashboard.proto
> +  google.protobuf.ListValue labels = 5;
Remove the `labels` filter

2022-11-02 01:50 UTC, whdalsrnt commented on proto/spaceone/api/dashboard/v1/domain_dashboard.proto
> +  enum Scope {
Add NONE type as follows:
- SCOPE_NONE
- DOMAIN
- USER

2022-11-02 01:50 UTC, whdalsrnt commented on proto/spaceone/api/dashboard/v1/domain_dashboard.proto
> +  enum Scope {
Add NONE type as follows:
- SCOPE_NONE
- DOMAIN
- USER

2022-11-02 01:50 UTC, whdalsrnt commented on proto/spaceone/api/dashboard/v1/domain_dashboard.proto
> +  enum Scope {
Add NONE type as follows:
- SCOPE_NONE
- DOMAIN
- USER

2022-11-02 01:50 UTC, whdalsrnt commented on proto/spaceone/api/dashboard/v1/project_dashboard.proto
> +  enum Scope {
Add NONE type as follows:
- SCOPE_NONE
- DOMAIN
- USER

2022-11-02 01:50 UTC, whdalsrnt commented on proto/spaceone/api/dashboard/v1/project_dashboard.proto
> +  enum Scope {
Add NONE type as follows:
- SCOPE_NONE
- DOMAIN
- USER

2022-11-02 01:50 UTC, whdalsrnt commented on proto/spaceone/api/dashboard/v1/project_dashboard.proto
> +  enum Scope {
Add NONE type as follows:
- SCOPE_NONE
- DOMAIN
- USER

2022-11-02 01:50 UTC, whdalsrnt commented on proto/spaceone/api/dashboard/v1/widget.proto
> +enum ViewMode {
Add NONE type as follows:
- VIEW_MODE_NONE
- AUTO
- FULL

2022-11-02 14:45 UTC, stat-kwon commented
There were 2 fixes based on code review.
- Removed labels field from query.
- Added None type to scope.

2022-11-03 06:35 UTC, whdalsrnt requested changes

2022-11-03 06:35 UTC, whdalsrnt commented on proto/spaceone/api/dashboard/v1/domain_dashboard.proto
> +  enum Scope {
The order of `NONE` values is set to 0.

2022-11-03 06:35 UTC, whdalsrnt commented on proto/spaceone/api/dashboard/v1/domain_dashboard.proto
> +  enum Scope {
The order of `NONE` values is set to 0.

2022-11-03 06:35 UTC, whdalsrnt commented on proto/spaceone/api/dashboard/v1/domain_dashboard.proto
> +  enum Scope {
The order of `NONE` values is set to 0.

2022-11-03 06:35 UTC, whdalsrnt commented on proto/spaceone/api/dashboard/v1/project_dashboard.proto
> +  enum Scope {
The order of `NONE` values is set to 0.

2022-11-03 06:35 UTC, whdalsrnt commented on proto/spaceone/api/dashboard/v1/project_dashboard.proto
> +  enum Scope {
The order of `NONE` values is set to 0.

2022-11-03 06:35 UTC, whdalsrnt commented on proto/spaceone/api/dashboard/v1/project_dashboard.proto
> +  enum Scope {
The order of `NONE` values is set to 0.

2022-11-03 06:35 UTC, whdalsrnt commented on proto/spaceone/api/dashboard/v1/widget.proto
> +enum ViewMode {
The order of `NONE` values is set to 0.

2022-11-03 13:34 UTC, WANZARGEN commented
Looks good to me !!!!

2022-11-05 17:23 UTC, stat-kwon commented
Overall protobuf change according to API document change in dashboard service
- Changed terminology and redesigned the overall structure
- Add project_id to project dashboard

2022-11-07 04:30 UTC, stat-kwon commented
We changed the terminology because widget_id is ambiguous from the point of view of api users.

AS-IS
- `widget_id`
- `name`

TO-BE
- `widget_name`
- `title`

Code review please. @whdalsrnt @jihyungSong

2022-11-08 08:04 UTC, stat-kwon commented
The following API has been added to add the version control function to the dashboard service.

**[DomainDashboard]**

- verb
        - DomainDashboard.delete_version
        - DomainDashboard.revert_version
        - DomainDashboard.get_version 
        - DomainDashboard.list_versions

- info
    -DomainDashboardVersionInfo


**[ProjectDashboard]**

- verb
        - ProjectDashboard.delete_version
        - ProjectDashboard.revert_version
        - ProjectDashboard.get_version 
        - ProjectDashboard.list_versions

- info
        - ProjectDashboardVersionInfo

2022-11-11 06:16 UTC, whdalsrnt approved these changes
It looks perfect code to me.

2022-11-11 06:16 UTC, merged